<?php
/**
 * Debug functions
 *
 * Contains functions to display and log errors and warnings.
 *
 * PHP version 5
 *
 * LICENSE: See LICENSE.md
 *
 * @package    viewpanelphp
 * @author     Al Wilde http://alwilde.com
 * @copyright  2009-2016 Al Wilde
 * @license    see LICENSE.md
 * @version    3.0.1
 */

function vp_error($code, $meaning, $use_error_array=false) {
    /**
    * Uses a loaded language file to display a View Panel error in a local language. Error output is controlled by settings.php
    * @param int   $code        The number of the View Panel error code
    * @return true if error has been processed correctly, false if something went wrong handling the error
    */
    
    //Are we being forced to use debug's own error array (this better be a fatal error)
    if ($use_error_array == true) {
        $error = array(
            "VP_ERR" => array(
                303 => array(
                    "text" => "Error 303: Loading localisation file failed."
                ),
                304 => array(
                    "text" => "Error 304: Debug options not set correctly."
                ),
                305 => array(
                    "text" => "Error 304: Debug options not set correctly."
                )
            )
            
            
        );
    } else {
        $error = vp_load_localisation();
    }
    
    //And dig out what caused it
    $backtrace = debug_backtrace();
    
    //Let's check our error from the file contains something
    $error = $error["VP_ERR"][$code]["text"];
    
    if ($error == "" or is_int($error)) {
        //The error code in the localisation file has given us nothing. Generic error time.
        if ($meaning == "fatal") {
            $error = "Error Code 103: unknown error code responding to: fatal error - " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
        } elseif ($meaning == "error") {
            $error = "Error Code 103: unknown error code responding to: nonfatal error - " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
        } elseif ($meaning == "warn") {
            $error = "Error Code 103: unknown error code responding to: warning - " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
        }
    } else {
        $error = "<p>" . $error . "</p><p>Generated by " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
    }
    
    //Now finally let's deal with our error
    if ($meaning == "fatal") {
        if (VP_DIE_ON_FATAL == true) {
            die($error);     //Fatal errors are always spat out
        }
    } elseif ($meaning == "error") {
        if (VP_DIE_ON_ERROR == true) {
            die($error);     //Fatal errors are always spat out
        }
    } elseif ($meaning == "warn") {
        if (VP_DIE_ON_WARN == true) {
            die($error);     //Fatal errors are always spat out
        }
    } else {
        echo "Error 305: View Panel error handling sprung a leak. An error has not been handled correctly.";
    }
        
}

function vp_mysql_error($code) {
    
}

function vp_http_error($code) {
    
} 

?>