<?php
/**
 * Debug functions
 *
 * Contains functions to display and log errors and warnings.
 *
 * PHP version 5
 *
 * LICENSE: See LICENSE.md
 *
 * @package    viewpanelphp
 * @author     Al Wilde http://alwilde.com
 * @copyright  2009-2016 Al Wilde
 * @license    see LICENSE.md
 * @version    3.0.1
 */

function vp_error($code, $meaning) {
    /**
    * Uses a loaded language file to display a View Panel error in a local language. Error output is controlled by settings.php
    * @param int   $code        The number of the View Panel error code
    * @return true if error has been processed correctly, false if something went wrong handling the error
    */
    
    //Let's dig out our error:
    $error = vp_load_localisation();
    
    //And dig out what caused it
    $backtrace = debug_backtrace();
    
    if (!$error) {
        //Oh dear, it appears loading the localisation file failed so we can't ouput the error in a local language. 
        //In that case let's try and force loading engb 
        $error = vp_load_localisation("engb");
        if (!$error) {
            //Forcing engb didn't work. Kill everything.
            echo "<p>vp_error was triggered after a code " . $code . " generated by:</p>";
            echo "<p>" . $backtrace[0]["file"] . ":" . $backtrace[0]["line"] . "</p>";
            echo "<p>vp_error failed to execute due to:</p>";
            echo "<p>Warning 302: Could not load localisation file defined in settings. Forcing engb.</p>";
            die("<p>Fatal Error 303: Loading engb localisation file failed.</p>");
        }
    }
    
    //Let's check our error from the file contains something
    $error = $error["VP_ERR"][$code]["text"];
    
    if ($error == "" or is_int($error)) {
        //The error code in the localisation file has given us nothing. Generic error time.
        if ($meaning == "fatal") {
            $error = "Error Code 103: unknown error code responding to: fatal error - " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
        } elseif ($meaning == "error") {
            $error = "Error Code 103: unknown error code responding to: nonfatal error - " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
        } elseif ($meaning == "warn") {
            $error = "Error Code 103: unknown error code responding to: warning - " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
        }
    } else {
        $error = "<p>" . $error . "</p><p>Generated by " . $backtrace[0]["file"] . ":" . $backtrace[0]["line"];
    }
    
    //Now finally let's deal with our error
    if ($meaning == "fatal") {
        if (VP_DIE_ON_FATAL == true) {
            die($error);     //Fatal errors are always spat out
        }
    } elseif ($meaning == "error") {
        if (VP_DIE_ON_ERROR == true) {
            die($error);     //Fatal errors are always spat out
        }
    } elseif ($meaning == "warn") {
        if (VP_DIE_ON_WARN == true) {
            die($error);     //Fatal errors are always spat out
        }
    } else {
        echo "Error 305: View Panel error handling sprung a leak. An error has not been handled correctly.";
    }
        
}

function vp_mysql_error($code) {
    
}

function vp_http_error($code) {
    
} 

?>